/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.confluent.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1712734369133487326L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.confluent.dto\",\"fields\":[{\"name\":\"street\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"city\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"state\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"geoLocation\",\"type\":{\"type\":\"record\",\"name\":\"GeoLocation\",\"fields\":[{\"name\":\"latitude\",\"type\":\"string\",\"default\":\"\",\"confluent:tags\":[\"PII\"]},{\"name\":\"longitude\",\"type\":\"string\",\"default\":\"\",\"confluent:tags\":[\"PII\"]}]},\"default\":{}},{\"name\":\"postalCode\",\"type\":\"string\",\"default\":\"\",\"confluent:tags\":[\"PII\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Address> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Address> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Address> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Address> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Address> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Address to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Address from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Address instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Address fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence street;
  private java.lang.CharSequence city;
  private java.lang.CharSequence state;
  private com.confluent.dto.GeoLocation geoLocation;
  private java.lang.CharSequence postalCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Address() {}

  /**
   * All-args constructor.
   * @param street The new value for street
   * @param city The new value for city
   * @param state The new value for state
   * @param geoLocation The new value for geoLocation
   * @param postalCode The new value for postalCode
   */
  public Address(java.lang.CharSequence street, java.lang.CharSequence city, java.lang.CharSequence state, com.confluent.dto.GeoLocation geoLocation, java.lang.CharSequence postalCode) {
    this.street = street;
    this.city = city;
    this.state = state;
    this.geoLocation = geoLocation;
    this.postalCode = postalCode;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return street;
    case 1: return city;
    case 2: return state;
    case 3: return geoLocation;
    case 4: return postalCode;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: street = (java.lang.CharSequence)value$; break;
    case 1: city = (java.lang.CharSequence)value$; break;
    case 2: state = (java.lang.CharSequence)value$; break;
    case 3: geoLocation = (com.confluent.dto.GeoLocation)value$; break;
    case 4: postalCode = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }


  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'geoLocation' field.
   * @return The value of the 'geoLocation' field.
   */
  public com.confluent.dto.GeoLocation getGeoLocation() {
    return geoLocation;
  }


  /**
   * Sets the value of the 'geoLocation' field.
   * @param value the value to set.
   */
  public void setGeoLocation(com.confluent.dto.GeoLocation value) {
    this.geoLocation = value;
  }

  /**
   * Gets the value of the 'postalCode' field.
   * @return The value of the 'postalCode' field.
   */
  public java.lang.CharSequence getPostalCode() {
    return postalCode;
  }


  /**
   * Sets the value of the 'postalCode' field.
   * @param value the value to set.
   */
  public void setPostalCode(java.lang.CharSequence value) {
    this.postalCode = value;
  }

  /**
   * Creates a new Address RecordBuilder.
   * @return A new Address RecordBuilder
   */
  public static com.confluent.dto.Address.Builder newBuilder() {
    return new com.confluent.dto.Address.Builder();
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Address RecordBuilder
   */
  public static com.confluent.dto.Address.Builder newBuilder(com.confluent.dto.Address.Builder other) {
    if (other == null) {
      return new com.confluent.dto.Address.Builder();
    } else {
      return new com.confluent.dto.Address.Builder(other);
    }
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Address instance.
   * @param other The existing instance to copy.
   * @return A new Address RecordBuilder
   */
  public static com.confluent.dto.Address.Builder newBuilder(com.confluent.dto.Address other) {
    if (other == null) {
      return new com.confluent.dto.Address.Builder();
    } else {
      return new com.confluent.dto.Address.Builder(other);
    }
  }

  /**
   * RecordBuilder for Address instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Address>
    implements org.apache.avro.data.RecordBuilder<Address> {

    private java.lang.CharSequence street;
    private java.lang.CharSequence city;
    private java.lang.CharSequence state;
    private com.confluent.dto.GeoLocation geoLocation;
    private com.confluent.dto.GeoLocation.Builder geoLocationBuilder;
    private java.lang.CharSequence postalCode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.confluent.dto.Address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.street)) {
        this.street = data().deepCopy(fields()[0].schema(), other.street);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.geoLocation)) {
        this.geoLocation = data().deepCopy(fields()[3].schema(), other.geoLocation);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasGeoLocationBuilder()) {
        this.geoLocationBuilder = com.confluent.dto.GeoLocation.newBuilder(other.getGeoLocationBuilder());
      }
      if (isValidValue(fields()[4], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[4].schema(), other.postalCode);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Address instance
     * @param other The existing instance to copy.
     */
    private Builder(com.confluent.dto.Address other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.street)) {
        this.street = data().deepCopy(fields()[0].schema(), other.street);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.geoLocation)) {
        this.geoLocation = data().deepCopy(fields()[3].schema(), other.geoLocation);
        fieldSetFlags()[3] = true;
      }
      this.geoLocationBuilder = null;
      if (isValidValue(fields()[4], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[4].schema(), other.postalCode);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }


    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.street = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder clearStreet() {
      street = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder setState(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'geoLocation' field.
      * @return The value.
      */
    public com.confluent.dto.GeoLocation getGeoLocation() {
      return geoLocation;
    }


    /**
      * Sets the value of the 'geoLocation' field.
      * @param value The value of 'geoLocation'.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder setGeoLocation(com.confluent.dto.GeoLocation value) {
      validate(fields()[3], value);
      this.geoLocationBuilder = null;
      this.geoLocation = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'geoLocation' field has been set.
      * @return True if the 'geoLocation' field has been set, false otherwise.
      */
    public boolean hasGeoLocation() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'geoLocation' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.confluent.dto.GeoLocation.Builder getGeoLocationBuilder() {
      if (geoLocationBuilder == null) {
        if (hasGeoLocation()) {
          setGeoLocationBuilder(com.confluent.dto.GeoLocation.newBuilder(geoLocation));
        } else {
          setGeoLocationBuilder(com.confluent.dto.GeoLocation.newBuilder());
        }
      }
      return geoLocationBuilder;
    }

    /**
     * Sets the Builder instance for the 'geoLocation' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.confluent.dto.Address.Builder setGeoLocationBuilder(com.confluent.dto.GeoLocation.Builder value) {
      clearGeoLocation();
      geoLocationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'geoLocation' field has an active Builder instance
     * @return True if the 'geoLocation' field has an active Builder instance
     */
    public boolean hasGeoLocationBuilder() {
      return geoLocationBuilder != null;
    }

    /**
      * Clears the value of the 'geoLocation' field.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder clearGeoLocation() {
      geoLocation = null;
      geoLocationBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'postalCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostalCode() {
      return postalCode;
    }


    /**
      * Sets the value of the 'postalCode' field.
      * @param value The value of 'postalCode'.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder setPostalCode(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.postalCode = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'postalCode' field has been set.
      * @return True if the 'postalCode' field has been set, false otherwise.
      */
    public boolean hasPostalCode() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'postalCode' field.
      * @return This builder.
      */
    public com.confluent.dto.Address.Builder clearPostalCode() {
      postalCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Address build() {
      try {
        Address record = new Address();
        record.street = fieldSetFlags()[0] ? this.street : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (geoLocationBuilder != null) {
          try {
            record.geoLocation = this.geoLocationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("geoLocation"));
            throw e;
          }
        } else {
          record.geoLocation = fieldSetFlags()[3] ? this.geoLocation : (com.confluent.dto.GeoLocation) defaultValue(fields()[3]);
        }
        record.postalCode = fieldSetFlags()[4] ? this.postalCode : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Address>
    WRITER$ = (org.apache.avro.io.DatumWriter<Address>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Address>
    READER$ = (org.apache.avro.io.DatumReader<Address>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.street);

    out.writeString(this.city);

    out.writeString(this.state);

    this.geoLocation.customEncode(out);

    out.writeString(this.postalCode);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);

      this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);

      this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);

      if (this.geoLocation == null) {
        this.geoLocation = new com.confluent.dto.GeoLocation();
      }
      this.geoLocation.customDecode(in);

      this.postalCode = in.readString(this.postalCode instanceof Utf8 ? (Utf8)this.postalCode : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);
          break;

        case 1:
          this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          break;

        case 2:
          this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          break;

        case 3:
          if (this.geoLocation == null) {
            this.geoLocation = new com.confluent.dto.GeoLocation();
          }
          this.geoLocation.customDecode(in);
          break;

        case 4:
          this.postalCode = in.readString(this.postalCode instanceof Utf8 ? (Utf8)this.postalCode : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










