/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.confluent.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreditCardInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2293227463208084370L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreditCardInfo\",\"namespace\":\"com.confluent.dto\",\"fields\":[{\"name\":\"cardNumber\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"cardPin\",\"type\":\"string\",\"default\":\"\",\"confluent:tags\":[\"PII\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreditCardInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreditCardInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreditCardInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreditCardInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreditCardInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreditCardInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreditCardInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreditCardInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreditCardInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence cardNumber;
  private java.lang.CharSequence cardPin;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreditCardInfo() {}

  /**
   * All-args constructor.
   * @param cardNumber The new value for cardNumber
   * @param cardPin The new value for cardPin
   */
  public CreditCardInfo(java.lang.CharSequence cardNumber, java.lang.CharSequence cardPin) {
    this.cardNumber = cardNumber;
    this.cardPin = cardPin;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cardNumber;
    case 1: return cardPin;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cardNumber = (java.lang.CharSequence)value$; break;
    case 1: cardPin = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cardNumber' field.
   * @return The value of the 'cardNumber' field.
   */
  public java.lang.CharSequence getCardNumber() {
    return cardNumber;
  }


  /**
   * Sets the value of the 'cardNumber' field.
   * @param value the value to set.
   */
  public void setCardNumber(java.lang.CharSequence value) {
    this.cardNumber = value;
  }

  /**
   * Gets the value of the 'cardPin' field.
   * @return The value of the 'cardPin' field.
   */
  public java.lang.CharSequence getCardPin() {
    return cardPin;
  }


  /**
   * Sets the value of the 'cardPin' field.
   * @param value the value to set.
   */
  public void setCardPin(java.lang.CharSequence value) {
    this.cardPin = value;
  }

  /**
   * Creates a new CreditCardInfo RecordBuilder.
   * @return A new CreditCardInfo RecordBuilder
   */
  public static com.confluent.dto.CreditCardInfo.Builder newBuilder() {
    return new com.confluent.dto.CreditCardInfo.Builder();
  }

  /**
   * Creates a new CreditCardInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreditCardInfo RecordBuilder
   */
  public static com.confluent.dto.CreditCardInfo.Builder newBuilder(com.confluent.dto.CreditCardInfo.Builder other) {
    if (other == null) {
      return new com.confluent.dto.CreditCardInfo.Builder();
    } else {
      return new com.confluent.dto.CreditCardInfo.Builder(other);
    }
  }

  /**
   * Creates a new CreditCardInfo RecordBuilder by copying an existing CreditCardInfo instance.
   * @param other The existing instance to copy.
   * @return A new CreditCardInfo RecordBuilder
   */
  public static com.confluent.dto.CreditCardInfo.Builder newBuilder(com.confluent.dto.CreditCardInfo other) {
    if (other == null) {
      return new com.confluent.dto.CreditCardInfo.Builder();
    } else {
      return new com.confluent.dto.CreditCardInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreditCardInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreditCardInfo>
    implements org.apache.avro.data.RecordBuilder<CreditCardInfo> {

    private java.lang.CharSequence cardNumber;
    private java.lang.CharSequence cardPin;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.confluent.dto.CreditCardInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cardNumber)) {
        this.cardNumber = data().deepCopy(fields()[0].schema(), other.cardNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cardPin)) {
        this.cardPin = data().deepCopy(fields()[1].schema(), other.cardPin);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CreditCardInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.confluent.dto.CreditCardInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cardNumber)) {
        this.cardNumber = data().deepCopy(fields()[0].schema(), other.cardNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cardPin)) {
        this.cardPin = data().deepCopy(fields()[1].schema(), other.cardPin);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'cardNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCardNumber() {
      return cardNumber;
    }


    /**
      * Sets the value of the 'cardNumber' field.
      * @param value The value of 'cardNumber'.
      * @return This builder.
      */
    public com.confluent.dto.CreditCardInfo.Builder setCardNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.cardNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cardNumber' field has been set.
      * @return True if the 'cardNumber' field has been set, false otherwise.
      */
    public boolean hasCardNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cardNumber' field.
      * @return This builder.
      */
    public com.confluent.dto.CreditCardInfo.Builder clearCardNumber() {
      cardNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cardPin' field.
      * @return The value.
      */
    public java.lang.CharSequence getCardPin() {
      return cardPin;
    }


    /**
      * Sets the value of the 'cardPin' field.
      * @param value The value of 'cardPin'.
      * @return This builder.
      */
    public com.confluent.dto.CreditCardInfo.Builder setCardPin(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.cardPin = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cardPin' field has been set.
      * @return True if the 'cardPin' field has been set, false otherwise.
      */
    public boolean hasCardPin() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cardPin' field.
      * @return This builder.
      */
    public com.confluent.dto.CreditCardInfo.Builder clearCardPin() {
      cardPin = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreditCardInfo build() {
      try {
        CreditCardInfo record = new CreditCardInfo();
        record.cardNumber = fieldSetFlags()[0] ? this.cardNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cardPin = fieldSetFlags()[1] ? this.cardPin : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreditCardInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreditCardInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreditCardInfo>
    READER$ = (org.apache.avro.io.DatumReader<CreditCardInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.cardNumber);

    out.writeString(this.cardPin);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.cardNumber = in.readString(this.cardNumber instanceof Utf8 ? (Utf8)this.cardNumber : null);

      this.cardPin = in.readString(this.cardPin instanceof Utf8 ? (Utf8)this.cardPin : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.cardNumber = in.readString(this.cardNumber instanceof Utf8 ? (Utf8)this.cardNumber : null);
          break;

        case 1:
          this.cardPin = in.readString(this.cardPin instanceof Utf8 ? (Utf8)this.cardPin : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










